In [2]:
# Simple
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [8]:
# to check dimension 
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]]])
print(arr.ndim)

3


In [10]:
# Indexing
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [26]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


In [30]:
# Array Shape
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]]])
print(arr.shape)

(1, 2, 3)


In [36]:
# Creating an array using ndim

import numpy as np 
arr = np.array([1, 2, 3, 4], ndmin=5) 
print(arr) 
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [40]:
# Array Reshaping

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
nr=arr.reshape(3,3)
print(nr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
# Convert the  1-D array with 12 elements into a 3-D array. 
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 
newarr = arr.reshape(2, 3, 2) 
print(newarr) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [44]:
# ValueError
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3) 
print(newarr) 

ValueError: cannot reshape array of size 8 into shape (3,3)

In [60]:
# Use of -1 for remaining elements
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8]) 
newarr = arr.reshape(2, 2,-1) 
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [62]:
# Array Iteration

import numpy as np
arr=np.array([1,2,3,4,5])
for x in arr:
    print(x)

1
2
3
4
5


In [68]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
for x in arr:
    print(x)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


In [88]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
for x in arr:
   for y in x:
       for z in y:
           print(z)

1
2
3
4
4
5
6
7


In [90]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
4
5
6
7


In [92]:
# Iterate through every scalar element of the 2D array skipping 1 element: 
import numpy as np 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) 
for x in np.nditer(arr[:, ::2]): 
  print(x) 

1
3
5
7


In [98]:
# Enumerate

import numpy as np 
arr = np.array([1, 2, 3]) 
for idx, x in np.ndenumerate(arr): 
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3
